package jujusvg

import (
	"bytes"
	"fmt"
	"testing"

	"github.com/ajstarks/svgo"
	. "gopkg.in/check.v1"
)

func Test(t *testing.T) { TestingT(t) }

type CanvasSuite struct{}

var _ = Suite(&CanvasSuite{})

func (s *CanvasSuite) TestServiceRender(c *C) {
	// Ensure that the Service's definition and usage methods output the
	// proper SVG elements.
	var buf bytes.Buffer
	svg := svg.New(&buf)
	service := Service{
		X:       0,
		Y:       0,
		IconUrl: "foo",
	}
	service.definition(svg)
	service.usage(svg)
	c.Assert(fmt.Sprintf("%s", buf.Bytes()), Equals,
		`<image x="0" y="0" width="96" height="96" xlink:href="foo" />`+"\n")
}

func (s *CanvasSuite) TestRelationRender(c *C) {
	// Ensure that the Relation's definition and usage methods output the
	// proper SVG elements.
	var buf bytes.Buffer
	svg := svg.New(&buf)
	relation := Relation{
		ServiceA: &Service{
			X: 0,
			Y: 0,
		},
		ServiceB: &Service{
			X: 100,
			Y: 100,
		},
	}
	relation.definition(svg)
	relation.usage(svg)
	c.Assert(fmt.Sprintf("%s", buf.Bytes()), Equals,
		`<line x1="48" y1="48" x2="148" y2="148" style="stroke:black"/>`+"\n")
}

func (s *CanvasSuite) TestGetRect(c *C) {
	// Ensure that the SVG is sized exactly around the positioned services.
	canvas := Canvas{}
	canvas.AddService(&Service{
		X: 0,
		Y: 0,
	})
	canvas.AddService(&Service{
		X: 100,
		Y: 100,
	})
	width, height := canvas.getRect()
	c.Assert(width, Equals, 196)
	c.Assert(height, Equals, 196)
	canvas.AddService(&Service{
		X: -100,
		Y: -100,
	})
	canvas.AddService(&Service{
		X: -100,
		Y: 100,
	})
	canvas.AddService(&Service{
		X: 100,
		Y: -100,
	})
	width, height = canvas.getRect()
	c.Assert(width, Equals, 296)
	c.Assert(height, Equals, 296)
}

func (s *CanvasSuite) TestMarshal(c *C) {
	// Ensure that the internal representation of the canvas can be marshalled
	// to SVG.
	var buf bytes.Buffer
	canvas := Canvas{}
	serviceA := &Service{
		X: 0,
		Y: 0,
	}
	serviceB := &Service{
		X: 100,
		Y: 100,
	}
	canvas.AddService(serviceA)
	canvas.AddService(serviceB)
	canvas.AddRelation(&Relation{
		ServiceA: serviceA,
		ServiceB: serviceB,
	})
	canvas.Marshal(&buf)
	c.Assert(fmt.Sprintf("%s", buf.Bytes()), Equals,
		`<?xml version="1.0"?>
<!-- Generated by SVGo -->
<svg width="196" height="196"
     xmlns="http://www.w3.org/2000/svg" 
     xmlns:xlink="http://www.w3.org/1999/xlink">
<defs>
</defs>
<g id="relations">
<line x1="48" y1="48" x2="148" y2="148" style="stroke:black"/>
</g>
<g id="services">
<image x="0" y="0" width="96" height="96" xlink:href="" />
<image x="100" y="100" width="96" height="96" xlink:href="" />
</g>
</svg>
`)
}
