package jujusvg

import (
	"io/ioutil"
	"net/http"

	"gopkg.in/errgo.v1"
	"gopkg.in/juju/charm.v5-unstable"
)

// An IconFetcher provides functionality for retrieving icons for the charms
// within a given bundle.  The FetchIcons function accepts a bundle, and
// returns a dict mapping charm paths to icon data.
type IconFetcher interface {
	FetchIcons(*charm.BundleData) (map[string]string, error)
}

// HttpFetcher is a default implementation of IconFetcher which retrieves charm
// icons from the web using the URL generated by IconURL on that charm.  The
// HTTP Client used may be overridden by an instance of http.Client.  The icons
// may optionally be fetched concurrently.
type HttpFetcher struct {
	FetchConcurrently bool
	IconURL           func(*charm.Reference) string
	Client            *http.Client
}

// FetchIcons retrieves icon SVGs over HTTP.  If specified in the struct, icons
// will be fetched concurrently.
func (h *HttpFetcher) FetchIcons(b *charm.BundleData) (map[string]string, error) {
	// If a client was not provided on creation, set a default.
	if h.Client == nil {
		h.Client = new(http.Client)
	}

	// Maintain a list of icons that have already been fetched.
	alreadyFetched := make(map[string]bool)

	// Channels for concurrent fetching.
	channels := [](chan bool){}
	errors := make(chan error, len(b.Services))

	// Build the map of icons.
	icons := make(map[string]string)
	for _, serviceData := range b.Services {
		charmId, err := charm.ParseReference(serviceData.Charm)
		if err != nil {
			return nil, errgo.Notef(err, "cannot parse charm %q", serviceData.Charm)
		}
		path := charmId.Path()

		// Don't duplicate icons in the map.
		if !alreadyFetched[path] {
			alreadyFetched[path] = true

			// Fetch concurrently or not, depending on option.
			if h.FetchConcurrently {
				done := make(chan bool, 1)
				channels = append(channels, done)
				go func() {
					icon, err := h.fetchIcon(h.IconURL(charmId), done)
					if err != nil {
						errors <- err
					} else {
						icons[path] = icon
					}
				}()
			} else {
				icon, err := h.fetchIcon(h.IconURL(charmId), nil)
				if err != nil {
					return nil, err
				}
				icons[path] = icon
			}
		}
	}

	// If fetching concurrently, block on receiving icon data; if any errors
	// occured, report them.
	if h.FetchConcurrently {
		for _, ch := range channels {
			<-ch
		}
		close(errors)
		for err := range errors {
			if err != nil {
				return nil, err
			}
		}
	}
	return icons, nil
}

// fetchIcon retrieves a single icon svg over HTTP.
func (h *HttpFetcher) fetchIcon(url string, done chan bool) (string, error) {
	resp, err := h.Client.Get(url)
	if err != nil {
		if done != nil {
			done <- true
		}
		return "", errgo.Newf("HTTP error fetching %s: %v", url, err)
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		if done != nil {
			done <- true
		}
		return "", errgo.Newf("Error retrieving icon from %s: %s", url, resp.Status)
	}
	body, err := ioutil.ReadAll(resp.Body)
	if err != nil {
		if done != nil {
			done <- true
		}
		return "", errgo.Newf("could not read icon data from url %s", url)
	}
	if done != nil {
		done <- true
	}
	return string(body), nil
}
